# Generated by Django 5.2.4 on 2025-07-23 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动名称')),
                ('description', models.TextField(verbose_name='活动描述')),
                ('date', models.DateTimeField(verbose_name='活动日期')),
                ('location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('slots', models.PositiveIntegerField(verbose_name='招募人数')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('phone', models.CharField(max_length=15, verbose_name='电话')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.activity', verbose_name='报名活动')),
            ],
        ),
    ]
