# Generated by Django 5.2.4 on 2025-07-23 07:43

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('education', '教育'), ('environment', '环保'), ('health', '医疗健康'), ('community', '社区服务'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类别'),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='活动有效'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='birthday',
            field=models.DateField(default=datetime.date(1990, 1, 1), verbose_name='生日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='报名时间'),
            preserve_default=False,
        ),
    ]
