# Generated by Django 5.2.4 on 2025-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_activity_category_activity_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='student_id',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
